name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake.svg

      - name: Commit and Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          add: dist/snake.svg
          message: "Generated snake animation"
